server {
    listen 80; #Puerto 80 o 8080? ..
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Resolver
    # 127.0.0.11 = DNS interno de Docker (funciona localmente)
    # En K8s el pod hereda el DNS de CoreDNS via /etc/resolv.conf,
    # pero igual necesitamos declarar resolver para usar variables
    # en proxy_pass (que es lo que evita el fallo al arrancar).
    resolver 127.0.0.11 valid=30s ipv6=off;

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Bonos service
    location /api/bonos/ {
        set $upstream_bonos bonos-service:8004;
        proxy_pass http://$upstream_bonos;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    #Apuestas service
    location /api/apuestas/ {
        set $upstream_apuestas apuestas-service:8005;
        proxy_pass http://$upstream_apuestas;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    #Estadísticas service
    location /api/estadisticas/ {
        set $upstream_estadisticas estadisticas-service:8006;
        proxy_pass http://$upstream_estadisticas;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    #Casino-backend catch-all (auth, usuarios, juegos, tx)
    location /api/ {
        set $upstream_backend casino-backend:3000;
        proxy_pass http://$upstream_backend;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health {
        set $upstream_health casino-backend:3000;
        proxy_pass http://$upstream_health/health;
    }

    # Cache de assets estáticos
    location ~* \.(?:js|css|woff2|svg|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
