apiVersion: apps/v1
kind: Deployment
metadata:
  name: casino-frontend
  labels:
    app: casino-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: casino-frontend
  template:
    metadata:
      labels:
        app: casino-frontend
    spec:
      containers:
        - name: casino-frontend
        #El pipeline reemplaza :latest conel SHA del commit antes del apply
        #imagen del ecr 
          image:image: 248357130561.dkr.ecr.us-east-1.amazonaws.com/casino-frontend:latest
          ports: 
            - containerPort: 8080

        #Nginx sirve contenido estatico liveness/readiness
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
